"""
02_feature_engineering.py — Telco MLOps Reference Architecture Feature Pipeline
================================================================================
Companion code for: "Telco MLOps Reference Architecture: Multi-Team, Multi-Model
at Scale" — Section 8 (Implementation Walkthrough), Code-02.

PURPOSE
-------
This script implements a production-quality feature engineering pipeline that
transforms raw PM counter data (generated by 01_synthetic_data.py) into a
feature matrix suitable for ML model training, validation, and serving.

The pipeline demonstrates:
  - Streaming-first design: features computed identically at training and serving
    time to eliminate training-serving skew (the #1 silent failure mode in
    production ML — see Section 7 discussion of Kappa architecture)
  - Point-in-time correct temporal splits (NEVER random for time series data)
  - Temporal features: rolling windows, deltas, cyclical encodings
  - Cross-KPI derived ratios (correlates with anomaly signatures)
  - Spatial peer-group z-scores (cell vs. cluster vs. site deviation)
  - Feature store naming conventions aligned with Feast entity model
    (entity: cell_id, timestamp — see CODE-02 in the whitepaper)
  - Proper handling of counter resets and missing values

DATA LINEAGE
------------
Input:  data/pm_counters.parquet      (from 01_synthetic_data.py)
        data/cell_topology.parquet    (from 01_synthetic_data.py)
Output: data/features_train.parquet
        data/features_val.parquet
        data/features_test.parquet
        data/feature_metadata.json    (feature names, stats, schema)

TEMPORAL SPLIT STRATEGY
-----------------------
Training-validation-test split on wall-clock time:
  Train:      first 60% of timeline
  Validation: next 20% of timeline
  Test:       final 20% of timeline
This respects temporal ordering and prevents future data leakage.

HOW TO RUN
----------
  # First generate data:
  python 01_synthetic_data.py

  # Then run this script:
  python 02_feature_engineering.py

  # Or run directly (will auto-generate data if not found):
  python 02_feature_engineering.py --regenerate-data

Requirements: Python 3.10+, pandas>=2.0, numpy>=1.24, scipy>=1.10,
              scikit-learn>=1.3

Coursebook cross-reference:
  - Chapter: Feature Engineering for Telco Data
  - Chapter: Time Series Analysis (windowed aggregations, cyclical encoding)
  - Chapter: MLOps Core (training-serving skew, point-in-time correctness)
"""

import argparse
import json
import logging
import os
import subprocess
import sys
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from scipy import stats as scipy_stats
from sklearn.preprocessing import RobustScaler

# ---------------------------------------------------------------------------
# Logging configuration — structured logs for pipeline observability
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("feature_engineering.log", mode="w"),
    ],
)
logger = logging.getLogger("feature_pipeline")

# Suppress noisy pandas performance warnings that don't affect correctness
warnings.filterwarnings("ignore", category=pd.errors.PerformanceWarning)

# ---------------------------------------------------------------------------
# Global constants — mirrors the Feast feature store schema from CODE-02
# ---------------------------------------------------------------------------
DATA_DIR = Path("data")
ROP_MINUTES = 15  # 3GPP PM counter granularity (15-minute reporting period)
SAMPLES_PER_HOUR = 60 // ROP_MINUTES  # = 4

# Rolling window sizes expressed in ROP count (not minutes) for clarity
WINDOW_1H = 4    # 1 hour   = 4 × 15-min ROPs
WINDOW_4H = 16   # 4 hours  = 16 × 15-min ROPs
WINDOW_24H = 96  # 24 hours = 96 × 15-min ROPs

# Minimum non-null fraction required before a rolling window feature is trusted
MIN_WINDOW_FILL = 0.5

# Peak-hour definition for LTE/NR networks (empirically: 08-10, 12-14, 18-21)
# See Coursebook Chapter on Telco Data Sources for diurnal traffic patterns
PEAK_HOURS = frozenset(range(8, 11)) | frozenset(range(12, 15)) | frozenset(range(18, 22))

# Temporal split ratios — must sum to 1.0
TRAIN_RATIO = 0.60
VAL_RATIO = 0.20
TEST_RATIO = 0.20

# Feature store entity column names (Feast convention: snake_case)
ENTITY_COLS = ["cell_id", "timestamp"]

# PM counter columns expected from 01_synthetic_data.py
# Named following 3GPP TS 28.552 NR PM counter conventions where possible
# (TS 28.550 governs the PM collection service architecture, not individual counter definitions)
REQUIRED_COUNTER_COLS = [
    "cell_id",
    "timestamp",
    "dl_prb_utilization",     # DL PRB utilization (0–1 fraction, pre-computed as
    # DL.PRBUsage.Active / DL.PRBUsage.Total in the O1 parser or Flink job.
    # 01_synthetic_data.py generates this directly as a fraction for simplicity.)
    "ul_prb_utilization",     # UL PRB utilization (0–1 fraction)
    "dl_throughput_mbps",     # DL user throughput (Mbps in synthetic data)
    # WARNING: Vendor unit differences for DRB.UEThpDl:
    #   Ericsson (pmRadioThpVolDl): kbits/ROP → Mbps = (kbits / 1000) / ROP_sec
    #   Nokia (e.g. DRB.IPThpVolDl): kbytes/ROP → Mbps = (kbytes × 8 / 1000) / ROP_sec
    #   Huawei: pre-computes a rate (kbps or Mbps) — do NOT divide by ROP_sec
    # Validate against your vendor PM counter reference manual before using.
    # Using the raw value directly produces ~900× error for 15-min ROPs (Ericsson)
    # or ~7200× error (Nokia, due to additional 8× kbytes→kbits factor).
    "ul_throughput_mbps",     # UL user throughput (same vendor conversion applies)
    "rrc_conn_active_ue",     # RRC-connected UEs (active)
    "rrc_conn_estab_att",     # RRC connection establishment attempts
    "rrc_conn_estab_succ",    # RRC connection establishment successes
    "cqi_mean",               # Mean CQI across UEs
    "rsrp_mean_dbm",          # Reference Signal Received Power (dBm)
    "rsrq_mean_db",           # Reference Signal Received Quality (dB)
    "pdsch_bler",             # PDSCH Block Error Rate (proxy for DL retx).
    # In synthetic data, pre-computed in 01_synthetic_data.py from CQI approximation.
    # In real PM files, compute from TB error/attempt counters:
    #   Ericsson: pmPdschTbInitialErrSR / pmPdschTbInitialAttemptsSR
    #   Nokia:    PDCP.SDU.DL.ErrNbr / PDCP.SDU.DL.TransNbr (approximate)
    # See §3 counter mapping table "Derived KPIs" for vendor-specific derivation.
    "ho_exec_att",            # Handover execution attempts
    "ho_exec_succ",           # Handover execution successes
    "is_anomaly",             # Ground truth label from 01_synthetic_data.py
]
# Note: 3GPP TS 28.552 counter names use dot notation (e.g., RRC.ConnEstab.Succ).
# This codebase uses snake_case equivalents (e.g., rrc_conn_estab_succ) following
# Python/Parquet conventions. Derived ratios (ho_success_ratio, rrc_setup_success_ratio,
# dl_retx_ratio) are computed in the feature engineering steps below from the raw
# attempt/success counters and BLER provided by 01_synthetic_data.py.

# Topology columns expected from 01_synthetic_data.py
REQUIRED_TOPOLOGY_COLS = [
    "cell_id",
    "site_id",
    "region",
    "sector",           # 1, 2, 3 (alpha, beta, gamma)
    "frequency_band",   # 3GPP band number
]
# Note: 01_synthetic_data.py does not produce cluster_id. When cluster_id is
# needed for spatial peer-group features, it is derived from site_id below.


# ---------------------------------------------------------------------------
# Data loading utilities
# ---------------------------------------------------------------------------

def load_pm_counters(data_dir: Path) -> pd.DataFrame:
    """
    Load and validate raw PM counter data from 01_synthetic_data.py output.

    Validates presence of required columns and correct dtypes. This mirrors
    the validation step in a real feature store's data ingestion contract
    (Great Expectations style — see Section 7 data quality discussion).
    """
    pm_path = data_dir / "pm_counters.parquet"
    if not pm_path.exists():
        raise FileNotFoundError(
            f"PM counter data not found at {pm_path}. "
            "Run 01_synthetic_data.py first, or use --regenerate-data flag."
        )

    logger.info("Loading PM counter data from %s", pm_path)
    df = pd.read_parquet(pm_path)
    logger.info("Loaded %d rows × %d columns", len(df), len(df.columns))

    # Validate required columns exist
    missing_cols = [c for c in REQUIRED_COUNTER_COLS if c not in df.columns]
    if missing_cols:
        raise ValueError(
            f"PM counter data missing required columns: {missing_cols}. "
            f"Available: {sorted(df.columns.tolist())}"
        )

    # Coerce timestamp to UTC-aware datetime (Feast requires UTC)
    if not pd.api.types.is_datetime64_any_dtype(df["timestamp"]):
        df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    elif df["timestamp"].dt.tz is None:
        df["timestamp"] = df["timestamp"].dt.tz_localize("UTC")

    # Sort by cell then time — required for rolling window correctness
    df = df.sort_values(["cell_id", "timestamp"]).reset_index(drop=True)

    logger.info(
        "Time range: %s → %s  |  Cells: %d  |  Anomaly rate: %.2f%%",
        df["timestamp"].min().isoformat(),
        df["timestamp"].max().isoformat(),
        df["cell_id"].nunique(),
        100.0 * df["is_anomaly"].mean(),
    )

    # ---------------------------------------------------------------
    # Derive ratio columns from raw attempt/success counters and BLER.
    # 01_synthetic_data.py provides raw counters; the ratios needed by
    # downstream feature engineering are computed here at load time.
    # ---------------------------------------------------------------
    eps = 1e-9
    df["ho_success_ratio"] = (
        df["ho_exec_succ"] / df["ho_exec_att"].clip(lower=eps)
    ).clip(0.0, 1.0)

    df["rrc_setup_success_ratio"] = (
        df["rrc_conn_estab_succ"] / df["rrc_conn_estab_att"].clip(lower=eps)
    ).clip(0.0, 1.0)

    # pdsch_bler is a reasonable proxy for DL retransmission ratio
    df["dl_retx_ratio"] = df["pdsch_bler"].clip(0.0, 1.0)

    logger.info("Derived ratios: ho_success_ratio, rrc_setup_success_ratio, dl_retx_ratio")

    return df


def load_cell_topology(data_dir: Path) -> pd.DataFrame:
    """
    Load cell topology metadata for spatial feature computation.

    Topology is static (changes only during network reconfiguration), so it
    is stored separately from time-series PM counters. In the feature store,
    this maps to a non-event FeatureView (Feast 'PushSource' or 'FileSource').
    """
    topo_path = data_dir / "cell_topology.parquet"
    if not topo_path.exists():
        logger.warning(
            "Topology file not found at %s — will skip spatial features.", topo_path
        )
        return pd.DataFrame(columns=REQUIRED_TOPOLOGY_COLS)

    logger.info("Loading cell topology from %s", topo_path)
    topo = pd.read_parquet(topo_path)

    # Accept a subset of columns if full topology is unavailable
    available = [c for c in REQUIRED_TOPOLOGY_COLS if c in topo.columns]
    missing = [c for c in REQUIRED_TOPOLOGY_COLS if c not in topo.columns]
    if missing:
        logger.warning("Topology missing optional columns: %s", missing)

    return topo[available].drop_duplicates(subset=["cell_id"])


# ---------------------------------------------------------------------------
# Temporal feature engineering
# ---------------------------------------------------------------------------

def add_cyclical_time_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Encode cyclical time variables using sine/cosine transformation.

    WHY CYCLICAL ENCODING?
    Raw integer hour (0-23) misleads the model: it implies hour 23 is "far"
    from hour 0, when in reality they are adjacent. Sine/cosine embedding
    puts hour 0 and hour 23 next to each other in feature space.
    This is standard practice for any periodic temporal feature.

    See Coursebook Chapter: Feature Engineering — Cyclical Encoding.

    Features produced (all prefixed 'tfe_' for temporal feature engineering):
      tfe_hour_sin, tfe_hour_cos        — hour of day (period = 24h)
      tfe_dow_sin, tfe_dow_cos          — day of week (period = 7 days)
      tfe_month_sin, tfe_month_cos      — month of year (period = 12 months)
      tfe_is_weekend                    — binary: Saturday or Sunday
      tfe_is_peak_hour                  — binary: within defined peak hours
    """
    logger.info("Computing cyclical time features...")
    ts = df["timestamp"]

    hour = ts.dt.hour.astype(float)
    dow = ts.dt.dayofweek.astype(float)   # Monday=0, Sunday=6
    month = (ts.dt.month - 1).astype(float)  # 0-indexed

    # Sine/cosine pairs for each periodicity
    df["tfe_hour_sin"] = np.sin(2 * np.pi * hour / 24.0)
    df["tfe_hour_cos"] = np.cos(2 * np.pi * hour / 24.0)
    df["tfe_dow_sin"] = np.sin(2 * np.pi * dow / 7.0)
    df["tfe_dow_cos"] = np.cos(2 * np.pi * dow / 7.0)
    df["tfe_month_sin"] = np.sin(2 * np.pi * month / 12.0)
    df["tfe_month_cos"] = np.cos(2 * np.pi * month / 12.0)

    # Binary convenience flags (interpretable; redundant with sin/cos but
    # help tree-based models like XGBoost make clean splits)
    df["tfe_is_weekend"] = (ts.dt.dayofweek >= 5).astype(np.int8)
    df["tfe_is_peak_hour"] = ts.dt.hour.isin(PEAK_HOURS).astype(np.int8)

    # Hour-of-day as raw integer (useful for gradient-boosted trees)
    df["tfe_hour_of_day"] = ts.dt.hour.astype(np.int8)
    df["tfe_day_of_week"] = ts.dt.dayofweek.astype(np.int8)

    return df


def add_rolling_statistics(
    df: pd.DataFrame,
    counter_cols: List[str],
    windows: Optional[Dict[str, int]] = None,
) -> pd.DataFrame:
    """
    Compute rolling statistics per-cell over multiple time windows.

    CRITICAL IMPLEMENTATION DETAIL — TRAINING-SERVING SKEW PREVENTION:
    Rolling windows must use min_periods to handle boundary cells at the start
    of a series. At serving time, recent cells may have fewer than window_size
    observations available. Setting min_periods = max(1, window // 2) allows
    partial windows while flagging insufficiently populated windows via the
    'coverage' feature. This ensures identical behavior at training and serving.

    The .shift(1) inside the rolling computation ensures that each row's
    rolling statistics are computed from PAST data only (no look-ahead leakage).
    This is point-in-time correct — the serving system can compute the same
    feature using only data available at the time of prediction.

    See Coursebook Chapter: MLOps Core — Point-in-Time Correctness.

    Args:
        df:            DataFrame sorted by [cell_id, timestamp]
        counter_cols:  PM counter columns to aggregate
        windows:       Dict mapping window name → window size in ROP units.
                       Defaults to 1h/4h/24h windows.

    Returns:
        DataFrame with added rolling feature columns prefixed 'rw_{stat}_{col}_{window}'.
    """
    if windows is None:
        windows = {"1h": WINDOW_1H, "4h": WINDOW_4H, "24h": WINDOW_24H}

    logger.info(
        "Computing rolling statistics for %d counters × %d windows...",
        len(counter_cols),
        len(windows),
    )

    # Group by cell — rolling windows must NEVER cross cell boundaries
    grouped = df.groupby("cell_id", sort=False)

    for window_name, window_size in windows.items():
        min_periods = max(1, window_size // 2)
        logger.debug("  Window %s (n=%d, min_periods=%d)", window_name, window_size, min_periods)

        for col in counter_cols:
            if col not in df.columns:
                logger.warning("  Column %s not found, skipping", col)
                continue

            # Shift by 1 to avoid including the current ROP in its own window
            # (prevents look-ahead: the current observation is what we're predicting)
            shifted = grouped[col].transform(lambda x: x.shift(1))

            # Build a temporary grouped series on the shifted values
            # We need to re-group because transform loses the groupby context
            shifted_grouped = shifted.groupby(df["cell_id"])

            # Rolling mean — central tendency over the window
            df[f"rw_mean_{col}_{window_name}"] = (
                shifted_grouped.transform(
                    lambda x: x.rolling(window=window_size, min_periods=min_periods).mean()
                )
            )

            # Rolling standard deviation — variability signal
            # std requires at least 2 periods; fill with 0 for single-observation windows
            df[f"rw_std_{col}_{window_name}"] = (
                shifted_grouped.transform(
                    lambda x: x.rolling(window=window_size, min_periods=min(2, min_periods)).std().fillna(0.0)
                )
            )

            # Rolling max — detects spikes (useful for anomaly detection)
            df[f"rw_max_{col}_{window_name}"] = (
                shifted_grouped.transform(
                    lambda x: x.rolling(window=window_size, min_periods=min_periods).max()
                )
            )

            # Rolling min — detects drops (useful for coverage/quality degradation)
            df[f"rw_min_{col}_{window_name}"] = (
                shifted_grouped.transform(
                    lambda x: x.rolling(window=window_size, min_periods=min_periods).min()
                )
            )

    logger.info("Rolling statistics complete. Feature count so far: %d", len(df.columns))
    return df


def add_delta_features(
    df: pd.DataFrame,
    counter_cols: List[str],
    lags: Optional[List[int]] = None,
) -> pd.DataFrame:
    """
    Compute first-order deltas (rate-of-change) and lagged values per cell.

    WHY DELTAS MATTER FOR ANOMALY DETECTION:
    Absolute KPI levels vary enormously by cell type (indoor vs. macro) and
    time-of-day. A 70% PRB utilization is normal at noon but alarming at 3am.
    Rate-of-change features are more stationary and anomaly-discriminative
    than absolute values, especially for sudden degradation events.

    Counter reset detection: In 3GPP PM, some counters can reset at ROP
    boundaries (wrapping at 2^32 for 32-bit counters). We detect these as
    large negative deltas and clip them to NaN, which propagates cleanly
    through downstream model pipelines.

    Args:
        df:           DataFrame sorted by [cell_id, timestamp]
        counter_cols: PM counter columns for which to compute deltas
        lags:         Lag periods to compute. Default: [1, 4] (1 ROP = 15min, 4 = 1h)

    Returns:
        DataFrame with added delta columns prefixed 'delta_{lag}_{col}'.
    """
    if lags is None:
        lags = [1, 4]  # 15min and 1h deltas

    logger.info("Computing delta/lag features for %d counters...", len(counter_cols))

    for lag in lags:
        for col in counter_cols:
            if col not in df.columns:
                continue

            # Compute lag within each cell group — cross-cell lag is meaningless
            lagged = df.groupby("cell_id")[col].transform(lambda x: x.shift(lag))

            # Raw lag value — useful as a direct input feature
            df[f"lag_{lag}_{col}"] = lagged

            # First-order delta (current - lagged)
            delta = df[col] - lagged
            col_name = f"delta_{lag}_{col}"

            # Counter reset detection: negative delta > 3× std is likely a reset,
            # not a real decrease. Flag and set to NaN rather than propagating
            # erroneous large negative values as legitimate signal.
            if col not in ("rsrp_mean_dbm", "rsrq_mean_db", "cqi_mean"):
                # Physical counters (counts, ratios, %) should never have massive drops
                # Signal-strength counters (dBm/dB) CAN legitimately swing large
                reset_threshold = lagged * 0.9  # Drop > 90% of prior value
                counter_reset_mask = (delta < -reset_threshold) & (lagged > 0)
                if counter_reset_mask.any():
                    logger.debug(
                        "  Counter reset detected: %d instances in %s lag=%d",
                        counter_reset_mask.sum(), col, lag
                    )
                delta[counter_reset_mask] = np.nan

            df[col_name] = delta

    logger.info("Delta features complete. Feature count so far: %d", len(df.columns))
    return df


# ---------------------------------------------------------------------------
# Cross-KPI ratio features
# ---------------------------------------------------------------------------

def add_cross_kpi_ratios(df: pd.DataFrame) -> pd.DataFrame:
    """
    Compute derived cross-KPI ratio features that capture joint degradation
    patterns not visible in individual counters.

    These ratios are domain-driven: each one reflects a known anomaly signature
    documented in telco RAN engineering literature.

    RATIO SEMANTICS:
    - Throughput efficiency: actual DL throughput vs. theoretical maximum
      given PRB usage. Drops below baseline indicate interference, scheduling
      inefficiency, or PDCP-layer issues.
    - Traffic asymmetry: DL/UL ratio. Sudden changes indicate asymmetric
      traffic anomalies (DDoS on UL, muted UL devices, etc.)
    - Quality degradation index: compound signal of CQI × (1 - retx_ratio),
      interpretable as "effective channel quality after retransmission cost."
    - Cell breathing indicator: active_ue / dl_prb_usage. High UE count with
      low PRB indicates either very efficient scheduling or PDCP buffering.
    - Spectral efficiency proxy: throughput / prb_usage. Drops indicate
      MCS degradation (interference, MIMO rank reduction).

    All ratios are protected against division by zero using np.where with
    a small epsilon. NaN propagation is intentional: if either operand is
    NaN, the ratio is NaN, which informs the model of data quality issues.
    """
    logger.info("Computing cross-KPI ratio features...")
    eps = 1e-6  # division guard

    # --- Spectral efficiency proxies ---
    # DL throughput per occupied PRB — drops indicate MCS degradation
    df["ratio_dl_tput_per_prb"] = np.where(
        df["dl_prb_utilization"] > eps,
        df["dl_throughput_mbps"] / (df["dl_prb_utilization"] + eps),
        np.nan,
    )

    # UL throughput per occupied UL PRB
    df["ratio_ul_tput_per_prb"] = np.where(
        df["ul_prb_utilization"] > eps,
        df["ul_throughput_mbps"] / (df["ul_prb_utilization"] + eps),
        np.nan,
    )

    # --- Traffic symmetry ---
    # DL/UL throughput ratio — deviations from cell baseline flag anomalies
    # Clipped at 100 to prevent extreme values from outlier ROPs
    df["ratio_dl_ul_throughput"] = np.clip(
        df["dl_throughput_mbps"] / (df["ul_throughput_mbps"] + eps),
        0.0,
        100.0,
    )

    # --- Quality degradation index ---
    # CQI × (1 - DL retx ratio): effective channel quality after retransmission cost
    # Range: 0 (catastrophic) to 15 (perfect channel, zero retx)
    df["kpi_quality_idx"] = df["cqi_mean"] * (1.0 - df["dl_retx_ratio"].clip(0.0, 1.0))

    # --- Handover stress indicator ---
    # HO success ratio × RRC setup success ratio: compound accessibility metric
    # Simultaneously low → likely coverage or congestion anomaly
    df["kpi_accessibility_compound"] = (
        df["ho_success_ratio"].clip(0.0, 1.0)
        * df["rrc_setup_success_ratio"].clip(0.0, 1.0)
    )

    # --- UE density vs. resource utilization ---
    # Active UE per PRB — high value = many UEs competing for few resources
    df["ratio_ue_per_prb_dl"] = np.where(
        df["dl_prb_utilization"] > eps,
        df["rrc_conn_active_ue"] / (df["dl_prb_utilization"] + eps),
        np.nan,
    )

    # --- Signal quality vs. throughput consistency ---
    # Expected: high RSRP → high CQI → high throughput. Breaks indicate
    # interference, UE capability issues, or scheduling problems.
    df["ratio_tput_per_cqi"] = np.where(
        df["cqi_mean"] > eps,
        df["dl_throughput_mbps"] / (df["cqi_mean"] + eps),
        np.nan,
    )

    # --- Retransmission ratio differential ---
    # UL - DL retransmission: normally near 0; large deviations indicate
    # link-direction-specific impairment
    # Note: ul_retx_ratio is not available from 01_synthetic_data.py (no UL BLER produced).
    # DL retx ratio (derived from pdsch_bler) is used standalone.

    # --- PRB saturation flag ---
    # Binary: PRB utilization > 0.80 (approaching saturation)
    # Note: dl_prb_utilization is a 0–1 fraction from 01_synthetic_data.py
    # This threshold is operationally meaningful: above 80%, scheduling
    # becomes non-optimal and latency degrades nonlinearly
    df["flag_prb_saturation"] = (df["dl_prb_utilization"] > 0.80).astype(np.int8)

    # --- Combined load index ---
    # Geometric mean of DL and UL PRB usage: single load indicator
    # Values are already 0–1 fractions; no /100 needed
    df["load_idx_geometric"] = np.sqrt(
        df["dl_prb_utilization"].clip(0.0, 1.0)
        * df["ul_prb_utilization"].clip(0.0, 1.0)
    )

    logger.info("Cross-KPI ratios complete. Feature count so far: %d", len(df.columns))
    return df


# ---------------------------------------------------------------------------
# Spatial peer-group deviation features
# ---------------------------------------------------------------------------

def add_spatial_peer_features(
    df: pd.DataFrame,
    topology: pd.DataFrame,
    kpi_cols: List[str],
) -> pd.DataFrame:
    """
    Compute z-score deviations of each cell relative to its peer group.

    WHY PEER-GROUP Z-SCORES?
    Absolute KPI thresholds fail because "normal" varies enormously between:
      - Indoor vs. outdoor cells (RSRP, throughput, UE count)
      - Urban vs. rural clusters (load, PRB usage, HO rate)
      - High-band vs. low-band sites (CQI, throughput, coverage)

    A cell with RSRP = -95 dBm is healthy in a dense urban cluster but
    potentially degraded in a rural macro cluster. The z-score captures
    "how different is this cell from its neighbors right now?"

    Peer groups are defined at two spatial granularities:
      1. cluster_id — typically 20-50 cells within a RAN cluster boundary
      2. region — entire region (coarser context)

    Z-score = (cell_value - cluster_mean) / (cluster_std + ε)

    The ε prevents division by zero when all cells in a cluster have the same
    value (common for binary flags and small clusters at night).

    PRODUCTION CONSIDERATION:
    At serving time, the cluster statistics (mean, std) must be computed from
    a recent time window (e.g., last 4 hours), not the current ROP's live
    statistics (which would include the cell being scored — data leakage).
    In a Feast feature store, this is implemented as a batch materialized view
    refreshed every 15 minutes, decoupled from real-time inference.

    See CODE-02 in the whitepaper for the Feast FeatureView implementation.
    """
    if topology.empty:
        logger.warning("Topology not available — skipping spatial peer features.")
        return df

    logger.info("Computing spatial peer-group deviation features...")

    # Derive cluster_id from site_id if not present in topology.
    # 01_synthetic_data.py does not produce cluster_id; we derive it by
    # grouping cells by site (cells on the same site share a cluster).
    # In production, cluster_id would come from the RAN planning tool.
    topo_cols = ["cell_id"]
    if "cluster_id" not in topology.columns:
        topology = topology.copy()
        topology["cluster_id"] = topology["site_id"]
        logger.info("Derived cluster_id from site_id (%d clusters)", topology["cluster_id"].nunique())
    topo_cols.append("cluster_id")
    if "frequency_band" in topology.columns:
        topo_cols.append("frequency_band")

    # Merge topology onto PM counters to get cluster membership and band info.
    # Note: "region" already exists in the PM DataFrame from 01_synthetic_data.py,
    # so we exclude it from the topology merge to avoid _x/_y column suffixes.
    df = df.merge(
        topology[topo_cols].drop_duplicates("cell_id"),
        on="cell_id",
        how="left",
    )

    # Handle cells not in topology (shouldn't happen in production, but be defensive)
    unmapped = df["cluster_id"].isna().sum()
    if unmapped > 0:
        logger.warning("%d rows have no topology mapping — spatial features will be NaN.", unmapped)

    eps = 1e-6

    # Compute z-score at cluster level (finer granularity — more useful signal)
    for col in kpi_cols:
        if col not in df.columns:
            continue

        # Cluster-level statistics — computed per (timestamp, cluster_id)
        # ⚠️ TRAINING-SERVING SKEW WARNING: Current implementation includes the
        # target cell in cluster mean/std. For the synthetic data (3 sectors per
        # site), this attenuates ALL z-scores by exactly 33% — not an edge case
        # but the systematic condition for the entire dataset.
        #
        # If the serving-time Flink job implements leave-one-out (as recommended),
        # the model will receive z-scores with different distributional properties
        # than it was trained on, degrading performance silently.
        #
        # -----------------------------------------------------------------
        # LEAVE-ONE-OUT peer statistics: exclude the target cell from its
        # own cluster mean/std so the z-score measures genuine deviation
        # from peers only.
        #
        # Formula:
        #   peer_mean = (cluster_sum - cell_value) / (n - 1)
        #   peer_std  = sqrt( (sum_sq_peers / (n-1)) - peer_mean² )
        #   z = (cell_value - peer_mean) / (peer_std + eps)
        #
        # For clusters of size <= 2, z-score is set to 0.0 (peer stats
        # are undefined or degenerate with only 0–1 peers).
        # -----------------------------------------------------------------
        grp = df.groupby(["timestamp", "cluster_id"])[col]
        cluster_sum = grp.transform("sum")
        cluster_count = grp.transform("count")
        cluster_sum_sq = df.groupby(["timestamp", "cluster_id"])[col].transform(
            lambda x: (x ** 2).sum()
        )

        peer_count = (cluster_count - 1).clip(lower=1)
        peer_mean = (cluster_sum - df[col]) / peer_count

        # Leave-one-out std via sum-of-squares
        peer_sum_sq = cluster_sum_sq - df[col] ** 2
        # NOTE: E[X²]-E[X]² formulation. Numerically stable for features
        # in typical PM counter ranges ([0,1] utilisation, [0,1000] throughput)
        # with float64. For very high-magnitude features or extreme cluster
        # sizes, catastrophic cancellation can produce small negative values
        # (caught by clip below). Production Flink implementations processing
        # features with magnitude >10⁴ should use Welford's online algorithm.
        peer_var = (peer_sum_sq / peer_count) - peer_mean ** 2
        neg_var_mask = peer_var < 0
        if neg_var_mask.any():
            neg_var_count = int(neg_var_mask.sum())
            logger.info(
                "Spatial z-score for %s: %d rows (%.2f%%) hit negative variance "
                "clip. If >5%%, investigate numerical precision (see Welford's note).",
                col, neg_var_count, 100.0 * neg_var_count / len(df),
            )
        peer_std = peer_var.clip(lower=0.0).pow(0.5)

        df[f"spatial_zscore_cluster_{col}"] = (
            (df[col] - peer_mean) / (peer_std + eps)
        ).clip(-5.0, 5.0)

        # Zero out z-scores for clusters too small for peer statistics
        small_mask = cluster_count <= 2
        df.loc[small_mask, f"spatial_zscore_cluster_{col}"] = 0.0
        if small_mask.any():
            logger.debug(
                "Zeroed %d z-scores in clusters of size <= 2 for %s",
                small_mask.sum(), col,
            )

        # Relative rank within cluster (0=lowest, 1=highest)
        # More robust than z-score when distributions are highly skewed
        df[f"spatial_rank_cluster_{col}"] = (
            df.groupby(["timestamp", "cluster_id"])[col]
            .rank(pct=True, na_option="keep")
        )

    logger.info("Spatial peer features (leave-one-out) complete. Feature count: %d", len(df.columns))
    return df


# ---------------------------------------------------------------------------
# Missing value treatment
# ---------------------------------------------------------------------------

def handle_missing_values(
    df: pd.DataFrame,
    numeric_cols: List[str],
    fill_strategy: str = "forward_fill",
) -> pd.DataFrame:
    """
    Handle missing values produced by rolling windows and counter resets.

    Strategy choices and rationale:
    - Rolling window boundary NaNs (first N rows per cell): forward-fill is
      inappropriate here since there is no prior value. We use 0 for ratio
      features (no change from baseline) and the column median for absolute
      KPIs (neutral imputation, won't introduce artificial signal).

    - Counter reset NaNs: forward-fill is appropriate — carry the last known
      good value until the counter stabilizes.

    - End-of-series NaNs: backward-fill is inappropriate (future leakage).
      Use median imputation.

    In production, the serving system must apply the SAME imputation strategy
    using pre-computed medians from the training set (stored in feature_metadata.json).
    This is a common source of training-serving skew when not carefully managed.

    Args:
        df:             Feature DataFrame
        numeric_cols:   Columns to check for missing values
        fill_strategy:  'forward_fill' or 'median'. Default: 'forward_fill'.
    """
    logger.info("Handling missing values in %d numeric columns...", len(numeric_cols))

    # Track imputation rates for monitoring (high imputation rate = data quality issue)
    imputation_stats = {}
    total_rows = len(df)

    for col in numeric_cols:
        if col not in df.columns:
            continue

        n_missing = df[col].isna().sum()
        if n_missing == 0:
            continue

        missing_pct = 100.0 * n_missing / total_rows
        imputation_stats[col] = missing_pct

        if missing_pct > 20.0:
            logger.warning(
                "  High missing rate for %s: %.1f%% (%d rows) — "
                "check upstream data quality",
                col, missing_pct, n_missing
            )

        if fill_strategy == "forward_fill":
            # Forward-fill within each cell (per-cell ffill, not global)
            df[col] = (
                df.groupby("cell_id")[col]
                .transform(lambda x: x.ffill())
            )
            # After per-cell ffill, any remaining NaN is at the START of a cell's
            # series (no prior value exists). Fill these with the global median.
            remaining = df[col].isna().sum()
            if remaining > 0:
                col_median = df[col].median()
                df[col].fillna(col_median, inplace=True)
        else:
            # Median imputation: compute from non-null values
            col_median = df[col].median()
            df[col].fillna(col_median, inplace=True)

    high_missing = {k: v for k, v in imputation_stats.items() if v > 5.0}
    if high_missing:
        logger.info(
            "Columns with >5%% missing (pre-imputation): %s",
            {k: f"{v:.1f}%" for k, v in sorted(high_missing.items(), key=lambda x: -x[1])}
        )

    logger.info("Missing value treatment complete.")
    return df


# ---------------------------------------------------------------------------
# Cell type one-hot encoding
# ---------------------------------------------------------------------------

def add_cell_type_encoding(df: pd.DataFrame) -> pd.DataFrame:
    """
    One-hot encode categorical cell metadata features.

    01_synthetic_data.py produces 'region' (urban/suburban/rural) and
    'frequency_band' (3GPP band number). 'cell_type' is not produced;
    we encode region instead. Band encoding groups by frequency range
    using the 3GPP band number.

    Uses explicit category lists to ensure consistent column presence across
    train/val/test splits and serving — a critical requirement for feature
    store materialization where not all categories may appear in every batch.
    """
    encoded = False

    # Region encoding (available from 01_synthetic_data.py via topology merge)
    if "region" in df.columns:
        logger.info("One-hot encoding region features...")
        region_categories = ["urban", "suburban", "rural"]
        for cat in region_categories:
            df[f"region_{cat}"] = (df["region"] == cat).astype(np.int8)
        encoded = True

    # Band encoding: group by 3GPP band number ranges
    # Low: bands 1-32 (sub-2.6 GHz), Mid: bands 33-77, High: bands 77+ (FR2/mmWave)
    if "frequency_band" in df.columns:
        df["band_low"] = (df["frequency_band"] <= 32).astype(np.int8)
        df["band_mid"] = ((df["frequency_band"] > 32) & (df["frequency_band"] <= 77)).astype(np.int8)
        df["band_high"] = (df["frequency_band"] > 77).astype(np.int8)
        encoded = True

    if not encoded:
        logger.warning("No categorical topology columns available — skipping encoding.")
        return df

    logger.info("Categorical encoding complete. Feature count so far: %d", len(df.columns))
    return df


# ---------------------------------------------------------------------------
# Feature selection and final feature set definition
# ---------------------------------------------------------------------------

def select_feature_columns(df: pd.DataFrame) -> Tuple[List[str], List[str]]:
    """
    Identify and separate feature columns from metadata and label columns.

    Feature naming convention (for Feast feature store integration):
      tfe_*      : temporal features (hour, day, cyclical encodings)
      rw_*       : rolling window statistics
      delta_*    : first-order deltas
      lag_*      : lagged values
      ratio_*    : cross-KPI ratios
      kpi_*      : derived composite KPI features
      spatial_*  : spatial peer-group deviation features
      flag_*     : binary indicator features
      load_*     : load index features
      celltype_* : cell type encoding
      band_*     : frequency band encoding

    Returns:
        feature_cols:  All feature columns (to be stored in feature store)
        metadata_cols: Non-feature columns (entities, label, raw counters)
    """
    # Columns that are entity keys or labels — NOT features
    non_feature_patterns = [
        "cell_id", "timestamp", "site_id", "cluster_id", "region",
        "sector", "frequency_band",
        "is_anomaly",  # target label
        "anomaly_type",  # label metadata (if present)
        "anomaly_subtype",
        # Ground-truth anomaly component columns — target leakage if included
        "anomaly_rrc_congestion", "anomaly_hw_degradation",
        "anomaly_counter_reset", "anomaly_traffic_spike",
    ]

    # Raw PM counter columns — these overlap with the derived rolling/delta
    # features computed FROM them. For tree-based models (XGBoost, Random Forest,
    # Isolation Forest) — the primary model types in this architecture — including
    # both raw and derived forms is intentional: tree models handle correlated
    # features robustly and benefit from access to both instantaneous and
    # aggregated values. For linear models or regularised regression, uncomment
    # the exclusion line below to remove raw counters and avoid coefficient
    # instability from multicollinearity.
    #
    # NOTE: Raw integer counters (rrc_conn_estab_att, ho_exec_att, etc.) are
    # scale-dependent — high-traffic cells produce larger values regardless of
    # anomaly status. This may bias the model toward cell size rather than
    # anomaly signatures. Production deployments should evaluate whether
    # normalizing raw counts by cell capacity (e.g., rrc_conn_estab_att /
    # max_ue_capacity) improves generalization across heterogeneous cell types.
    raw_counter_cols = [
        "dl_prb_utilization", "ul_prb_utilization",
        "dl_throughput_mbps", "ul_throughput_mbps",
        "rrc_conn_active_ue",
        "cqi_mean", "rsrp_mean_dbm", "rsrq_mean_db",
        "dl_retx_ratio",
        "ho_success_ratio", "rrc_setup_success_ratio",
        # Raw attempt/success counters (used to derive ratios above)
        "rrc_conn_estab_att", "rrc_conn_estab_succ",
        "ho_exec_att", "ho_exec_succ",
        "pdsch_bler",
    ]

    excluded_cols = set(non_feature_patterns)
    # Uncomment the following line to exclude raw counters (recommended for linear models):
    # excluded_cols.update(raw_counter_cols)

    feature_cols = [
        col for col in df.columns
        if col not in excluded_cols
        and pd.api.types.is_numeric_dtype(df[col])
    ]

    metadata_cols = [col for col in df.columns if col in excluded_cols]

    return feature_cols, metadata_cols


# ---------------------------------------------------------------------------
# Temporal train/val/test splitting
# ---------------------------------------------------------------------------

def temporal_train_val_test_split(
    df: pd.DataFrame,
    train_ratio: float = TRAIN_RATIO,
    val_ratio: float = VAL_RATIO,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Split the feature DataFrame into train/validation/test sets using
    temporal ordering.

    WHY TEMPORAL SPLIT (NEVER RANDOM):
    Random splitting of time-series data creates look-ahead bias: the model
    sees future patterns during training (e.g., a recurring anomaly pattern
    at a specific time of day seen in the 'future' test set appears in
    training). This inflates evaluation metrics and causes production
    disappointment.

    The split is on GLOBAL wall-clock timestamps, not per-cell. This ensures:
    1. All cells have the same evaluation horizon (fair comparison)
    2. Temporal dependencies at the fleet level are respected
    3. Seasonal patterns unseen during training are properly evaluated

    Split points:
      Train:  [t_start, t_train_end)
      Val:    [t_train_end, t_val_end)   ← gap of 0 allowed (no overlap)
      Test:   [t_val_end, t_end]

    In production, the validation set is used for hyperparameter tuning
    and early stopping. The test set is held out until final evaluation.
    Re-use of the test set for tuning is a protocol violation.

    See Coursebook Chapter: Model Evaluation — Temporal Cross-Validation.
    """
    test_ratio = 1.0 - train_ratio - val_ratio

    # Compute split boundaries from global timestamp range
    t_min = df["timestamp"].min()
    t_max = df["timestamp"].max()
    total_duration = (t_max - t_min).total_seconds()

    t_train_end = t_min + pd.Timedelta(seconds=total_duration * train_ratio)
    t_val_end = t_min + pd.Timedelta(seconds=total_duration * (train_ratio + val_ratio))

    # Align to nearest ROP boundary (15-min) for cleanliness
    rop_td = pd.Timedelta(minutes=ROP_MINUTES)
    t_train_end = t_train_end.floor(rop_td)
    t_val_end = t_val_end.floor(rop_td)

    train = df[df["timestamp"] < t_train_end].copy()
    val = df[(df["timestamp"] >= t_train_end) & (df["timestamp"] < t_val_end)].copy()
    test = df[df["timestamp"] >= t_val_end].copy()

    # Validate no overlap and no gap (gap = wasted data, overlap = leakage)
    assert train["timestamp"].max() < val["timestamp"].min(), "Train/val overlap detected!"
    assert val["timestamp"].max() < test["timestamp"].min(), "Val/test overlap detected!"

    logger.info(
        "Temporal split:\n"
        "  Train: %s → %s  (%d rows, %.1f%% of data, anomaly rate: %.2f%%)\n"
        "  Val:   %s → %s  (%d rows, %.1f%% of data, anomaly rate: %.2f%%)\n"
        "  Test:  %s → %s  (%d rows, %.1f%% of data, anomaly rate: %.2f%%)",
        train["timestamp"].min().isoformat(), train["timestamp"].max().isoformat(),
        len(train), 100.0 * len(train) / len(df),
        100.0 * train["is_anomaly"].mean(),
        val["timestamp"].min().isoformat(), val["timestamp"].max().isoformat(),
        len(val), 100.0 * len(val) / len(df),
        100.0 * val["is_anomaly"].mean(),
        test["timestamp"].min().isoformat(), test["timestamp"].max().isoformat(),
        len(test), 100.0 * len(test) / len(df),
        100.0 * test["is_anomaly"].mean(),
    )

    return train, val, test


# ---------------------------------------------------------------------------
# Feature scaling (fit on train only, apply to all splits)
# ---------------------------------------------------------------------------

def fit_and_apply_scaling(
    train: pd.DataFrame,
    val: pd.DataFrame,
    test: pd.DataFrame,
    feature_cols: List[str],
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, RobustScaler, Dict]:
    """
    Fit RobustScaler on training data only, then apply to all splits.

    WHY ROBUSTSCALER:
    RobustScaler uses median and IQR instead of mean and std, making it
    resilient to the extreme values common in telco data (burst traffic,
    anomaly spikes). StandardScaler would be pulled towards outliers and
    distort the feature distributions for the majority of normal observations.

    WHY FIT ON TRAIN ONLY:
    Fitting (computing statistics) on validation or test data leaks information
    about the future into the training process. The scaler parameters are part
    of the model pipeline and must be learned only from training data.
    This is a subtle but critical requirement — see Coursebook Chapter: MLOps
    Core for the "preprocessing leak" anti-pattern.

    Returns:
        Scaled train/val/test DataFrames, the fitted scaler, and scaling stats.
    """
    logger.info("Fitting RobustScaler on training data (%d features)...", len(feature_cols))

    # Only scale features that exist in the DataFrame
    available_features = [f for f in feature_cols if f in train.columns]

    scaler = RobustScaler(
        with_centering=True,
        with_scaling=True,
        quantile_range=(5.0, 95.0),  # More aggressive than default (25-75) for telco outliers
    )

    # Fit ONLY on training data
    scaler.fit(train[available_features].fillna(0.0))

    # Apply to all splits
    train = train.copy()
    val = val.copy()
    test = test.copy()

    train[available_features] = scaler.transform(train[available_features].fillna(0.0))
    val[available_features] = scaler.transform(val[available_features].fillna(0.0))
    test[available_features] = scaler.transform(test[available_features].fillna(0.0))

    # Record scaling statistics for the feature store / serving pipeline
    # These must be shipped alongside the model artifact for serving-time use
    scaling_stats = {
        col: {
            "center": float(scaler.center_[i]),
            "scale": float(scaler.scale_[i]),
        }
        for i, col in enumerate(available_features)
    }

    logger.info("Scaling applied to train/val/test splits.")
    return train, val, test, scaler, scaling_stats


# ---------------------------------------------------------------------------
# Feature metadata export (for feature store registration)
# ---------------------------------------------------------------------------

def build_feature_metadata(
    df: pd.DataFrame,
    feature_cols: List[str],
    scaling_stats: Dict,
    train_df: pd.DataFrame,
) -> Dict:
    """
    Build feature metadata JSON for feature store registration and monitoring.

    This metadata is used by:
    1. The Feast feature store registration script (CODE-02) to define
       FeatureView schemas with correct dtypes.
    2. The drift detection pipeline (CODE-06) as the reference distribution
       against which serving-time features are compared.
    3. The model card generator (CODE-04) to document feature statistics.

    The training distribution statistics (mean, std, percentiles) computed
    here become the reference distribution for Wasserstein-distance drift detection
    drift detection at serving time.

    See Coursebook Chapter: Monitoring and Observability — Distribution Drift.
    """
    logger.info("Building feature metadata for feature store registration...")

    available_features = [f for f in feature_cols if f in train_df.columns]

    feature_metadata = {
        "schema_version": "1.0",
        "created_at": pd.Timestamp.now(tz="UTC").isoformat(),
        "entity_columns": ENTITY_COLS,
        "feature_count": len(available_features),
        "rop_minutes": ROP_MINUTES,
        "train_rows": len(train_df),
        "train_time_range": {
            "start": train_df["timestamp"].min().isoformat(),
            "end": train_df["timestamp"].max().isoformat(),
        },
        "features": {},
    }

    for col in available_features:
        if col not in train_df.columns:
            continue

        series = train_df[col].dropna()
        if len(series) == 0:
            continue

        # Distribution statistics used for drift detection (Wasserstein, KS test)
        feature_metadata["features"][col] = {
            "dtype": str(train_df[col].dtype),
            "missing_pct_train": float(100.0 * train_df[col].isna().mean()),
            "stats": {
                "mean": float(series.mean()),
                "std": float(series.std()),
                "min": float(series.min()),
                "p01": float(series.quantile(0.01)),
                "p05": float(series.quantile(0.05)),
                "p25": float(series.quantile(0.25)),
                "p50": float(series.quantile(0.50)),
                "p75": float(series.quantile(0.75)),
                "p95": float(series.quantile(0.95)),
                "p99": float(series.quantile(0.99)),
                "max": float(series.max()),
            },
            "scaling": scaling_stats.get(col, {}),
        }

    logger.info(
        "Feature metadata built for %d features.",
        len(feature_metadata["features"]),
    )
    return feature_metadata


# ---------------------------------------------------------------------------
# Feature correlation / importance diagnostics
# ---------------------------------------------------------------------------

def log_feature_diagnostics(
    train: pd.DataFrame,
    feature_cols: List[str],
    target_col: str = "is_anomaly",
    top_n: int = 20,
) -> None:
    """
    Log diagnostic statistics about feature quality.

    Checks:
    1. Near-zero variance features (likely useless or constant)
    2. Top features by absolute Pearson correlation with target
    3. Pairwise high-correlation pairs (multicollinearity warning)

    This is a quick sanity check, not a full feature selection pipeline.
    Feature selection should be done with model-based importance in 03_model_training.py.
    """
    logger.info("Running feature diagnostics (top %d by target correlation)...", top_n)

    available = [f for f in feature_cols if f in train.columns]

    # --- Near-zero variance check ---
    variances = train[available].var()
    low_var = variances[variances < 1e-6].index.tolist()
    if low_var:
        logger.warning(
            "  %d near-zero variance features (consider dropping): %s",
            len(low_var),
            low_var[:10],
        )

    # --- Correlation with target ---
    if target_col in train.columns:
        target_corr = (
            train[available + [target_col]]
            .corr()[target_col]
            .drop(target_col)
            .abs()
            .sort_values(ascending=False)
        )

        logger.info("  Top %d features by |correlation| with %s:", top_n, target_col)
        for feat, corr_val in target_corr.head(top_n).items():
            logger.info("    %-55s  r = %.4f", feat, corr_val)

    # --- High pairwise correlation warning ---
    # Compute only on top-50 features to keep runtime manageable
    top_50 = target_corr.head(50).index.tolist() if target_col in train.columns else available[:50]
    if len(top_50) > 1:
        corr_matrix = train[top_50].corr().abs()
        # Extract upper triangle
        upper = corr_matrix.where(
            np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
        )
        high_corr_pairs = [
            (col, row, upper.loc[row, col])
            for col in upper.columns
            for row in upper.index
            if pd.notna(upper.loc[row, col]) and upper.loc[row, col] > 0.95
        ]
        if high_corr_pairs:
            logger.info(
                "  %d highly correlated feature pairs (r > 0.95) — "
                "consider deduplication:",
                len(high_corr_pairs),
            )
            for a, b, r in sorted(high_corr_pairs, key=lambda x: -x[2])[:10]:
                logger.info("    %s ↔ %s  r=%.4f", a, b, r)


# ---------------------------------------------------------------------------
# Save outputs
# ---------------------------------------------------------------------------

def save_feature_splits(
    train: pd.DataFrame,
    val: pd.DataFrame,
    test: pd.DataFrame,
    feature_cols: List[str],
    feature_metadata: Dict,
    data_dir: Path,
    scaler: RobustScaler,
) -> None:
    """
    Save train/val/test feature splits to Parquet and write feature metadata JSON.

    Parquet format is preferred over CSV because:
    1. Schema preservation — dtypes are stored (no string→float coercion on reload)
    2. Compression — typically 5-10× smaller than CSV for numeric data
    3. Columnar access — downstream training scripts can load only needed columns
    4. Native support in Feast, Spark, and DuckDB (the offline store backends)

    Output files:
        data/features_train.parquet  — Training features + label + entity keys
        data/features_val.parquet    — Validation features + label + entity keys
        data/features_test.parquet   — Test features + label + entity keys
        data/feature_metadata.json   — Schema, statistics, scaling params
    """
    data_dir.mkdir(parents=True, exist_ok=True)

    # Columns to include in output: entity keys + features + label
    output_cols = (
        [c for c in ENTITY_COLS if c in train.columns]
        + [f for f in feature_cols if f in train.columns]
        + ["is_anomaly"]
        # Include raw counters in output for reference/debugging even though
        # they are not in the model feature set.
        # NOTE: If RobustScaler is enabled (fit_and_apply_scaling), ALL numeric
        # columns in the output Parquet are scaled. Raw (unscaled) counter values
        # are NOT preserved. To access raw values, load from data/pm_counters.parquet.
        + [c for c in train.columns if c in [
            "dl_prb_utilization", "ul_prb_utilization", "dl_throughput_mbps",
            "ul_throughput_mbps", "rrc_conn_active_ue", "cqi_mean", "rsrp_mean_dbm",
        ]]
    )
    # Deduplicate while preserving order
    seen = set()
    output_cols = [c for c in output_cols if not (c in seen or seen.add(c))]
    output_cols = [c for c in output_cols if c in train.columns]

    for split_name, split_df in [("train", train), ("val", val), ("test", test)]:
        out_path = data_dir / f"features_{split_name}.parquet"
        split_df[output_cols].to_parquet(out_path, index=False, compression="snappy")
        logger.info(
            "Saved %s split: %s  (%d rows × %d columns, %.1f MB)",
            split_name,
            out_path,
            len(split_df),
            len(output_cols),
            out_path.stat().st_size / (1024 * 1024),
        )

    # Feature metadata JSON — used by serving pipeline and drift monitoring
    # Record scaling status so downstream consumers know value semantics
    feature_metadata["scaling_applied"] = True
    feature_metadata["scaling_method"] = "RobustScaler(quantile_range=(5.0, 95.0))"
    feature_metadata["scaling_note"] = (
        "All numeric feature columns in features_{train,val,test}.parquet are "
        "RobustScaler-transformed. Raw (unscaled) values are in data/pm_counters.parquet. "
        "The scaler is persisted at data/feature_scaler.joblib. "
        "03_model_training.py saves models/tier2_random_forest.joblib as a "
        "sklearn.pipeline.Pipeline with the scaler embedded (when "
        "feature_scaler.joblib is available). When loading the Pipeline artifact "
        "with pre-scaled Parquet features, extract the bare classifier via "
        "model.named_steps['clf'] to avoid double-scaling. For production serving "
        "with raw features from the online store, use the full Pipeline. "
        "Tier-1 models (isolation_forest, ocsvm) expect pre-scaled input and "
        "do not embed a scaler."
    )

    feature_metadata["reference_distribution_space"] = "training_scaled"
    feature_metadata["reference_distribution_note"] = (
        "Feature statistics in this file are computed on RobustScaler-transformed "
        "training data. These stats are for model debugging and feature importance "
        "analysis, NOT for drift detection reference distributions."
    )
    feature_metadata["drift_monitoring_path"] = "pre_scaling_ratios"
    feature_metadata["drift_monitoring_note"] = (
        "For drift detection, load reference distributions from the pre-scaling "
        "derived ratio columns (dl_prb_utilization, ho_success_ratio, "
        "rrc_setup_success_ratio, etc.) computed by 02_feature_engineering.py "
        "BEFORE fit_and_apply_scaling() is called — not from these scaled Parquet "
        "splits. See whitepaper §7 'Monitoring data spaces' callout."
    )

    # Persist the fitted scaler for downstream inverse-transform
    scaler_path = data_dir / "feature_scaler.joblib"
    import joblib as _joblib
    _joblib.dump(scaler, scaler_path)
    logger.info("Feature scaler saved to %s", scaler_path)

    metadata_path = data_dir / "feature_metadata.json"
    with open(metadata_path, "w") as f:
        json.dump(feature_metadata, f, indent=2, default=str)
    logger.info("Feature metadata saved to %s", metadata_path)


# ---------------------------------------------------------------------------
# Complete pipeline orchestration
# ---------------------------------------------------------------------------

def run_feature_pipeline(data_dir: Path = DATA_DIR) -> Dict:
    """
    Execute the complete feature engineering pipeline end-to-end.

    Pipeline steps:
    1.  Load PM counters and cell topology
    2.  Add cyclical temporal features (hour, day, month encodings)
    3.  Add rolling window statistics (1h, 4h, 24h)
    4.  Add delta/lag features (15min, 1h lags)
    5.  Add cross-KPI ratio features
    6.  Merge topology and add spatial peer-group z-scores
    7.  Add cell type one-hot encoding
    8.  Handle missing values (forward-fill + median imputation)
    9.  Select feature columns
    10. Temporal train/val/test split (60/20/20)
    11. Fit RobustScaler on train, apply to all splits
    12. Build feature metadata (for feature store + drift monitoring)
    13. Log diagnostic statistics
    14. Save outputs to Parquet

    Returns:
        Summary dictionary with split sizes, feature count, anomaly rates.
    """
    logger.info("=" * 70)
    logger.info("TELCO MLOPS FEATURE ENGINEERING PIPELINE")
    logger.info("Whitepaper: Multi-Team, Multi-Model at Scale")
    logger.info("Feast entity: cell_id | window: %d-minute ROP", ROP_MINUTES)
    logger.info("=" * 70)

    # -------------------------------------------------------------------------
    # Step 1: Load data
    # -------------------------------------------------------------------------
    pm = load_pm_counters(data_dir)
    topology = load_cell_topology(data_dir)

    initial_shape = pm.shape
    logger.info("Step 1: Data loaded. Shape: %s", initial_shape)

    # -------------------------------------------------------------------------
    # Step 2: Temporal features
    # -------------------------------------------------------------------------
    pm = add_cyclical_time_features(pm)
    logger.info("Step 2: Temporal features added.")

    # -------------------------------------------------------------------------
    # Step 3: Rolling window statistics
    # -------------------------------------------------------------------------
    # These are the most expensive features to compute — O(N × W × C) complexity.
    # In production, computed incrementally by the Flink streaming job.
    counter_cols_for_rolling = [
        "dl_prb_utilization",
        "ul_prb_utilization",
        "dl_throughput_mbps",
        "ul_throughput_mbps",
        "rrc_conn_active_ue",
        "cqi_mean",
        "rsrp_mean_dbm",
        "rsrq_mean_db",
        "dl_retx_ratio",
        "ho_success_ratio",
        "rrc_setup_success_ratio",
    ]

    # NOTE: For demonstration we use a subset of counters × windows to keep
    # runtime manageable. In production, all counters get all windows.
    # The 24h window can be dropped for latency-critical (Near-RT RIC) use cases.
    pm = add_rolling_statistics(
        pm,
        counter_cols=counter_cols_for_rolling,
        windows={"1h": WINDOW_1H, "4h": WINDOW_4H, "24h": WINDOW_24H},
    )
    logger.info("Step 3: Rolling statistics added.")

    # -------------------------------------------------------------------------
    # Step 4: Delta and lag features
    # -------------------------------------------------------------------------
    delta_cols = [
        "dl_prb_utilization",
        "ul_prb_utilization",
        "dl_throughput_mbps",
        "rrc_conn_active_ue",
        "cqi_mean",
        "rsrp_mean_dbm",
        "dl_retx_ratio",
        "ho_success_ratio",
    ]
    pm = add_delta_features(pm, counter_cols=delta_cols, lags=[1, 4])
    logger.info("Step 4: Delta/lag features added.")

    # -------------------------------------------------------------------------
    # Step 5: Cross-KPI ratio features
    # -------------------------------------------------------------------------
    pm = add_cross_kpi_ratios(pm)
    logger.info("Step 5: Cross-KPI ratios added.")

    # -------------------------------------------------------------------------
    # Step 6: Spatial peer-group features
    # -------------------------------------------------------------------------
    spatial_kpi_cols = [
        "dl_prb_utilization",
        "dl_throughput_mbps",
        "rrc_conn_active_ue",
        "rsrp_mean_dbm",
        "cqi_mean",
        "dl_retx_ratio",
    ]
    pm = add_spatial_peer_features(pm, topology=topology, kpi_cols=spatial_kpi_cols)
    logger.info("Step 6: Spatial peer features added.")

    # -------------------------------------------------------------------------
    # Step 7: Cell type encoding
    # -------------------------------------------------------------------------
    pm = add_cell_type_encoding(pm)
    logger.info("Step 7: Cell type encoding added.")

    # -------------------------------------------------------------------------
    # Step 8: Missing value treatment
    # -------------------------------------------------------------------------
    numeric_cols = pm.select_dtypes(include=[np.number]).columns.tolist()
    pm = handle_missing_values(pm, numeric_cols=numeric_cols, fill_strategy="forward_fill")
    logger.info("Step 8: Missing values handled.")

    # Log final null count as a data quality indicator
    remaining_nulls = pm[numeric_cols].isna().sum().sum()
    if remaining_nulls > 0:
        logger.warning(
            "Remaining null values after imputation: %d (may affect model training)",
            remaining_nulls,
        )

    # -------------------------------------------------------------------------
    # Step 9: Feature column selection
    # -------------------------------------------------------------------------
    feature_cols, metadata_cols = select_feature_columns(pm)
    logger.info(
        "Step 9: Feature selection — %d features, %d metadata/label columns",
        len(feature_cols),
        len(metadata_cols),
    )

    # -------------------------------------------------------------------------
    # Step 10: Temporal train/val/test split
    # -------------------------------------------------------------------------
    train_df, val_df, test_df = temporal_train_val_test_split(pm)
    logger.info("Step 10: Temporal split applied.")

    # -------------------------------------------------------------------------
    # Step 11: Feature scaling
    # -------------------------------------------------------------------------
    # Save pre-scaling reference for drift detection BEFORE scaling.
    # The DriftDetector expects raw (unscaled) derived ratio columns.
    #
    # NOTE: This reference contains ALL pre-scaling engineered features (~150 columns)
    # plus entity columns (cell_id, timestamp). For serving-time drift detection
    # (which monitors only the subset of features available in the online store),
    # the 05_production_patterns.py --use-pipeline-model path intersects feature_names
    # with available columns in both reference and production DataFrames, automatically
    # filtering to the common set. The full reference is saved here to support both
    # training-time drift analysis (all features) and serving-time monitoring (subset).
    #
    # IMPORTANT: Include raw ratio columns (dl_prb_utilization, ho_success_ratio, etc.)
    # even if they are excluded from the model feature set (e.g., if someone uncomments
    # the raw_counter_cols exclusion in select_feature_columns()), because the
    # DriftDetector monitors serving-time feature distributions which include these.
    _DRIFT_RATIO_COLS = [
        "dl_prb_utilization", "ul_prb_utilization", "ho_success_ratio",
        "rrc_setup_success_ratio", "dl_retx_ratio",
    ]
    entity_cols = ["cell_id", "timestamp"]
    drift_ref_cols = list(set(
        [c for c in entity_cols if c in train_df.columns]
        + feature_cols
        + [c for c in _DRIFT_RATIO_COLS if c in train_df.columns]
    ))
    raw_reference_path = data_dir / "features_raw_reference.parquet"
    train_df[drift_ref_cols].to_parquet(raw_reference_path, index=False, compression="snappy")
    logger.info("Saved pre-scaling drift reference: %s (%d rows, %d cols incl. %d ratio cols)",
                raw_reference_path, len(train_df), len(drift_ref_cols),
                sum(1 for c in _DRIFT_RATIO_COLS if c in train_df.columns))

    train_df, val_df, test_df, scaler, scaling_stats = fit_and_apply_scaling(
        train_df, val_df, test_df, feature_cols
    )
    logger.info("Step 11: RobustScaler fitted on train, applied to all splits.")

    # -------------------------------------------------------------------------
    # Step 12: Feature metadata
    # -------------------------------------------------------------------------
    feature_metadata = build_feature_metadata(
        df=pm,
        feature_cols=feature_cols,
        scaling_stats=scaling_stats,
        train_df=train_df,
    )
    logger.info("Step 12: Feature metadata built.")

    # -------------------------------------------------------------------------
    # Step 13: Feature diagnostics
    # -------------------------------------------------------------------------
    log_feature_diagnostics(train_df, feature_cols, target_col="is_anomaly", top_n=20)
    logger.info("Step 13: Feature diagnostics logged.")

    # -------------------------------------------------------------------------
    # Step 14: Save outputs
    # -------------------------------------------------------------------------
    save_feature_splits(
        train=train_df,
        val=val_df,
        test=test_df,
        feature_cols=feature_cols,
        feature_metadata=feature_metadata,
        data_dir=data_dir,
        scaler=scaler,
    )
    logger.info("Step 14: Outputs saved.")

    # -------------------------------------------------------------------------
    # Summary
    # -------------------------------------------------------------------------
    summary = {
        "input_rows": initial_shape[0],
        "input_cols": initial_shape[1],
        "engineered_feature_count": len(feature_cols),
        "train_rows": len(train_df),
        "val_rows": len(val_df),
        "test_rows": len(test_df),
        "train_anomaly_rate_pct": float(100.0 * train_df["is_anomaly"].mean()),
        "val_anomaly_rate_pct": float(100.0 * val_df["is_anomaly"].mean()),
        "test_anomaly_rate_pct": float(100.0 * test_df["is_anomaly"].mean()),
        "output_files": [
            str(DATA_DIR / "features_train.parquet"),
            str(DATA_DIR / "features_val.parquet"),
            str(DATA_DIR / "features_test.parquet"),
            str(DATA_DIR / "feature_metadata.json"),
        ],
    }

    logger.info("=" * 70)
    logger.info("PIPELINE COMPLETE")
    logger.info("  Input:             %d rows × %d raw columns", summary["input_rows"], summary["input_cols"])
    logger.info("  Engineered features: %d", summary["engineered_feature_count"])
    logger.info("  Train:  %6d rows  (anomaly rate: %.2f%%)", summary["train_rows"], summary["train_anomaly_rate_pct"])
    logger.info("  Val:    %6d rows  (anomaly rate: %.2f%%)", summary["val_rows"], summary["val_anomaly_rate_pct"])
    logger.info("  Test:   %6d rows  (anomaly rate: %.2f%%)", summary["test_rows"], summary["test_anomaly_rate_pct"])
    logger.info("=" * 70)

    return summary


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Telco MLOps Feature Engineering Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python 02_feature_engineering.py
  python 02_feature_engineering.py --data-dir /mnt/data/pm
  python 02_feature_engineering.py --regenerate-data
        """,
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=DATA_DIR,
        help="Directory containing PM counter Parquet files (default: ./data)",
    )
    parser.add_argument(
        "--regenerate-data",
        action="store_true",
        default=False,
        help="Re-run 01_synthetic_data.py to regenerate source data before feature engineering",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging verbosity (default: INFO)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    # Adjust log level from CLI argument
    logging.getLogger().setLevel(getattr(logging, args.log_level))
    logging.getLogger("feature_pipeline").setLevel(getattr(logging, args.log_level))

    # Optionally regenerate source data
    if args.regenerate_data:
        logger.info("Regenerating synthetic data via 01_synthetic_data.py...")
        result = subprocess.run(
            [sys.executable, "01_synthetic_data.py"],
            capture_output=False,
            check=True,
        )
        logger.info("Data generation complete (exit code: %d)", result.returncode)

    # Check for data files before running
    pm_path = args.data_dir / "pm_counters.parquet"
    if not pm_path.exists():
        logger.error(
            "PM counter data not found at %s. "
            "Run '01_synthetic_data.py' first, or use the --regenerate-data flag.",
            pm_path,
        )
        sys.exit(1)

    # Execute the pipeline
    summary = run_feature_pipeline(data_dir=args.data_dir)

    # Print a concise summary table to stdout for CI/CD pipeline parsing
    print("\n" + "=" * 60)
    print("FEATURE ENGINEERING SUMMARY")
    print("=" * 60)
    for key, val in summary.items():
        if key == "output_files":
            print(f"  {'output_files':<30}: {len(val)} files written")
            for f in val:
                print(f"    → {f}")
        elif isinstance(val, float):
            print(f"  {key:<30}: {val:.4f}")
        else:
            print(f"  {key:<30}: {val}")
    print("=" * 60)
    print("\nNext step: python 03_model_training.py")
    print("           (reads data/features_train.parquet, data/features_val.parquet)")
